# Generated by Django 4.1.5 on 2023-01-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='likey',
            field=models.IntegerField(default=0),
        ),
    ]
