# Generated by Django 4.1.5 on 2023-01-12 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shop_content_shop_likey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
