# Generated by Django 4.1.5 on 2023-01-12 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='name',
            new_name='nae',
        ),
    ]
