# Generated by Django 4.1.5 on 2023-01-12 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_name_shop_nae'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='nae',
            new_name='name',
        ),
    ]
